input_file: "data/all_texts.json"
output_folder: "embeddings"
window_size: 3
curruption_rate: 0.8
num_of_negatives: 10
batch_size: 1024
emb_dim: 200
epochs: 120
initial_lr: 0.005
use_cuda: true
print_every: 2

